# Generated by Django 2.0.1 on 2018-01-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(max_length=10000),
        ),
    ]
