# Generated by Django 2.0.1 on 2018-01-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180107_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='myPhoto')),
            ],
        ),
    ]
