# Generated by Django 2.0.1 on 2018-01-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180107_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
