# Generated by Django 2.0.1 on 2018-01-07 07:55

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='photo',
            field=models.FileField(storage=user_profile.models.OverwriteStorage(), upload_to='myPhoto'),
        ),
    ]
