# Generated by Django 2.0.1 on 2018-01-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180109_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
