# Generated by Django 2.0.1 on 2018-01-07 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('postID', models.UUIDField()),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('postID', models.UUIDField()),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('userID', models.CharField(max_length=100, unique=True)),
                ('postID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo', models.FileField(upload_to='postPhoto')),
                ('upWear', models.CharField(max_length=500)),
                ('downWear', models.CharField(max_length=500)),
                ('shoes', models.CharField(max_length=500)),
                ('accessories', models.CharField(max_length=500)),
                ('weather', models.CharField(max_length=100)),
                ('temp', models.IntegerField()),
            ],
        ),
    ]
