# Generated by Django 2.0.1 on 2018-01-07 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180107_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iconClass',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
